"""Initial migration

Revision ID: 31a5dae9a143
Revises: 
Create Date: 2024-12-27 19:13:31.646140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31a5dae9a143'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('neighborhood',
    sa.Column('neigh_num', sa.Integer(), nullable=False),
    sa.Column('neigh_name', sa.String(length=255), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('neigh_num')
    )
    op.create_index(op.f('ix_neighborhood_neigh_num'), 'neighborhood', ['neigh_num'], unique=False)
    op.create_table('listings',
    sa.Column('airbnb_id', sa.Integer(), nullable=False),
    sa.Column('airbnb_name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('neigh_num', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['neigh_num'], ['neighborhood.neigh_num'], ),
    sa.PrimaryKeyConstraint('airbnb_id')
    )
    op.create_index(op.f('ix_listings_airbnb_id'), 'listings', ['airbnb_id'], unique=False)
    op.create_table('room',
    sa.Column('airbnb_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.String(length=255), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=True),
    sa.Column('check_out', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['airbnb_id'], ['listings.airbnb_id'], ),
    sa.PrimaryKeyConstraint('airbnb_id')
    )
    op.create_index(op.f('ix_room_airbnb_id'), 'room', ['airbnb_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_airbnb_id'), table_name='room')
    op.drop_table('room')
    op.drop_index(op.f('ix_listings_airbnb_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_neighborhood_neigh_num'), table_name='neighborhood')
    op.drop_table('neighborhood')
    # ### end Alembic commands ###
